[2025-07-15T09:57:52.880+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-15T09:57:52.895+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.dbt_run scheduled__2025-06-01T00:00:00+00:00 [queued]>
[2025-07-15T09:57:52.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.dbt_run scheduled__2025-06-01T00:00:00+00:00 [queued]>
[2025-07-15T09:57:52.899+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-15T09:57:52.910+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-06-01 00:00:00+00:00
[2025-07-15T09:57:52.913+0000] {standard_task_runner.py:63} INFO - Started process 8893 to run task
[2025-07-15T09:57:52.916+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'dbt_run', 'scheduled__2025-06-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt.py', '--cfg-path', '/tmp/tmpb8fg0bpn']
[2025-07-15T09:57:52.917+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask dbt_run
[2025-07-15T09:57:52.959+0000] {task_command.py:426} INFO - Running <TaskInstance: run_dbt_models.dbt_run scheduled__2025-06-01T00:00:00+00:00 [running]> on host ZeeLaptop.localdomain
[2025-07-15T09:57:53.016+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-01T00:00:00+00:00'
[2025-07-15T09:57:53.017+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-15T09:57:53.018+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-15T09:57:53.018+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /home/reach2zeeshan/clinicaltrials &&\n        source venv/bin/activate &&\n        dbt run\n        ']
[2025-07-15T09:57:53.026+0000] {subprocess.py:86} INFO - Output:
[2025-07-15T09:57:53.064+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 4: dbt: command not found
[2025-07-15T09:57:53.064+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-07-15T09:57:53.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-15T09:57:53.070+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-07-15T09:57:53.073+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_dbt_models, task_id=dbt_run, run_id=scheduled__2025-06-01T00:00:00+00:00, execution_date=20250601T000000, start_date=20250715T095752, end_date=20250715T095753
[2025-07-15T09:57:53.087+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 8893)
[2025-07-15T09:57:53.129+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-15T09:57:53.140+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T09:57:53.141+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
