[2025-07-15T10:10:25.341+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-15T10:10:25.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.dbt_test scheduled__2025-07-14T20:00:00+00:00 [queued]>
[2025-07-15T10:10:25.356+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.dbt_test scheduled__2025-07-14T20:00:00+00:00 [queued]>
[2025-07-15T10:10:25.356+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-15T10:10:25.371+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2025-07-14 20:00:00+00:00
[2025-07-15T10:10:25.374+0000] {standard_task_runner.py:63} INFO - Started process 9777 to run task
[2025-07-15T10:10:25.375+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'dbt_test', 'scheduled__2025-07-14T20:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt.py', '--cfg-path', '/tmp/tmpvi55xfo9']
[2025-07-15T10:10:25.376+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask dbt_test
[2025-07-15T10:10:25.415+0000] {task_command.py:426} INFO - Running <TaskInstance: run_dbt_models.dbt_test scheduled__2025-07-14T20:00:00+00:00 [running]> on host ZeeLaptop.localdomain
[2025-07-15T10:10:25.505+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-14T20:00:00+00:00'
[2025-07-15T10:10:25.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-15T10:10:25.508+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-15T10:10:25.509+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /home/reach2zeeshan/clinicaltrials &&\n        /home/reach2zeeshan/clinicaltrials/venv/bin/dbt test\n        ']
[2025-07-15T10:10:25.517+0000] {subprocess.py:86} INFO - Output:
[2025-07-15T10:10:27.131+0000] {subprocess.py:93} INFO - [0m10:10:27  Running with dbt=1.10.4
[2025-07-15T10:10:27.520+0000] {subprocess.py:93} INFO - [0m10:10:27  Registered adapter: snowflake=1.10.0
[2025-07-15T10:10:28.051+0000] {subprocess.py:93} INFO - [0m10:10:28  Found 2 models, 2 data tests, 1 source, 476 macros
[2025-07-15T10:10:28.053+0000] {subprocess.py:93} INFO - [0m10:10:28
[2025-07-15T10:10:28.053+0000] {subprocess.py:93} INFO - [0m10:10:28  Concurrency: 1 threads (target='dev')
[2025-07-15T10:10:28.053+0000] {subprocess.py:93} INFO - [0m10:10:28
[2025-07-15T10:10:30.105+0000] {subprocess.py:93} INFO - [0m10:10:30  1 of 2 START test dbt_expectations_expect_column_values_to_be_between_int_sponsor_summary_early_stop_rate__1__0__False  [RUN]
[2025-07-15T10:10:30.128+0000] {subprocess.py:93} INFO - [0m10:10:30  1 of 2 ERROR dbt_expectations_expect_column_values_to_be_between_int_sponsor_summary_early_stop_rate__1__0__False  [[31mERROR[0m in 0.02s]
[2025-07-15T10:10:30.129+0000] {subprocess.py:93} INFO - [0m10:10:30  2 of 2 START test not_null_stg_ctgov__studies_nct_id ........................... [RUN]
[2025-07-15T10:10:30.513+0000] {subprocess.py:93} INFO - [0m10:10:30  2 of 2 PASS not_null_stg_ctgov__studies_nct_id ................................. [[32mPASS[0m in 0.38s]
[2025-07-15T10:10:31.075+0000] {subprocess.py:93} INFO - [0m10:10:31
[2025-07-15T10:10:31.076+0000] {subprocess.py:93} INFO - [0m10:10:31  Finished running 2 data tests in 0 hours 0 minutes and 3.02 seconds (3.02s).
[2025-07-15T10:10:31.189+0000] {subprocess.py:93} INFO - [0m10:10:31
[2025-07-15T10:10:31.190+0000] {subprocess.py:93} INFO - [0m10:10:31  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-07-15T10:10:31.190+0000] {subprocess.py:93} INFO - [0m10:10:31
[2025-07-15T10:10:31.191+0000] {subprocess.py:93} INFO - [0m10:10:31  [31mFailure in test dbt_expectations_expect_column_values_to_be_between_int_sponsor_summary_early_stop_rate__1__0__False (models/stg_ctgov__studies.yaml)[0m
[2025-07-15T10:10:31.191+0000] {subprocess.py:93} INFO - [0m10:10:31    Compilation Error in test dbt_expectations_expect_column_values_to_be_between_int_sponsor_summary_early_stop_rate__1__0__False (models/stg_ctgov__studies.yaml)
[2025-07-15T10:10:31.191+0000] {subprocess.py:93} INFO -   'dbt_expectations' is undefined. This can happen when calling a macro that does not exist. Check for typos and/or install package dependencies with "dbt deps".
[2025-07-15T10:10:31.191+0000] {subprocess.py:93} INFO - [0m10:10:31
[2025-07-15T10:10:31.192+0000] {subprocess.py:93} INFO - [0m10:10:31  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=2
[2025-07-15T10:10:32.815+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-15T10:10:32.816+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-15T10:10:32.819+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-15T10:10:32.822+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_dbt_models, task_id=dbt_test, run_id=scheduled__2025-07-14T20:00:00+00:00, execution_date=20250714T200000, start_date=20250715T101025, end_date=20250715T101032
[2025-07-15T10:10:32.832+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 9777)
[2025-07-15T10:10:32.841+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-15T10:10:32.846+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T10:10:32.847+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
