[2025-07-15T11:01:57.432+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-15T11:01:57.442+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt_models.ingest_data manual__2025-07-15T10:50:45.194882+00:00 [queued]>
[2025-07-15T11:01:57.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt_models.ingest_data manual__2025-07-15T10:50:45.194882+00:00 [queued]>
[2025-07-15T11:01:57.446+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-07-15T11:01:57.461+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): ingest_data> on 2025-07-15 10:50:45.194882+00:00
[2025-07-15T11:01:57.463+0000] {standard_task_runner.py:63} INFO - Started process 2719 to run task
[2025-07-15T11:01:57.466+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'run_dbt_models', 'ingest_data', 'manual__2025-07-15T10:50:45.194882+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt.py', '--cfg-path', '/tmp/tmp9g7bdi52']
[2025-07-15T11:01:57.467+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask ingest_data
[2025-07-15T11:01:57.501+0000] {task_command.py:426} INFO - Running <TaskInstance: run_dbt_models.ingest_data manual__2025-07-15T10:50:45.194882+00:00 [running]> on host ZeeLaptop.localdomain
[2025-07-15T11:01:57.556+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_dbt_models' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T10:50:45.194882+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T10:50:45.194882+00:00'
[2025-07-15T11:01:57.557+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-15T11:01:57.558+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-15T11:01:57.559+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        /home/reach2zeeshan/clinicaltrials/venv/bin/python /home/reach2zeeshan/clinicaltrials/ingestion/data_ingestion.py\n        ']
[2025-07-15T11:01:57.563+0000] {subprocess.py:86} INFO - Output:
[2025-07-15T11:01:57.664+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-15T11:01:57.664+0000] {subprocess.py:93} INFO -   File "/home/reach2zeeshan/clinicaltrials/ingestion/data_ingestion.py", line 5, in <module>
[2025-07-15T11:01:57.664+0000] {subprocess.py:93} INFO -     import pandas as pd
[2025-07-15T11:01:57.664+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pandas'
[2025-07-15T11:01:57.679+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-15T11:01:57.679+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-15T11:01:57.683+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reach2zeeshan/clinicaltrials/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-15T11:01:57.686+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=run_dbt_models, task_id=ingest_data, run_id=manual__2025-07-15T10:50:45.194882+00:00, execution_date=20250715T105045, start_date=20250715T110157, end_date=20250715T110157
[2025-07-15T11:01:57.696+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task ingest_data (Bash command failed. The command returned a non-zero exit code 1.; 2719)
[2025-07-15T11:01:57.719+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-15T11:01:57.730+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T11:01:57.737+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
